# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b03e88ac6d17d7699c0c04e09ef9b5d8a274cc91ff7f9b9528c8f66ab2a132fa856d877c5e056bd167e168ba1117fb83da4c82cc1fb745d14b519c2f7fb6f5

test:
  secret_key_base: 6e653f97878704ea5fb110b84e2bbe13ac9fa18826190fa1508301f199f72087fe9d5dac2448c2d044f9d071eff71c90cddc47b2c5023e9cd58f117504ecb851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
